### PR TITLE
Fix custom `getter`s with `class_call` objects

### LINKED ISSUE #469: Custom `getter` / `setter` evaluates objects of `class_call`
``` r
library(S7)
Foo <- new_class("Foo", class_call)
foo <- Foo(quote(stop("boom")))
foo
#> <Foo>  language stop("boom")

Foo <- new_class("Foo", class_call, properties = list(
  bar = new_property(getter = function(self) {
    self # evaluates `stop('boom')` call
    "bar"
  })
))

Foo(quote(stop("boom")))@bar
#> Error in (function (self) : boom

traceback()
#> No traceback available
```

Related: The error message + traceback from a custom getter/setter is not very helpful.

### PR DESCRIPTION
**Pull request by t-kalinowski**
Fixes #469

### CODE REVIEW

**Comment by t-kalinowski** [comment]
Is there a better way to protect a call object from evaluation by `Rf_eval()` than wrapping the object in `base::quote()`?

File: R/zzz.R [hunk 1]
```diff
@@ -82,9 +82,10 @@ is_S7_type <- function(x) {
 }
 
 check_subsettable <- function(x, allow_env = FALSE) {
-  allowed_types <- c("list", if (allow_env) "environment")
+  allowed_types <- c("list", if (allow_env) "environment",
+                     "language", "pairlist")
   if (!typeof(x) %in% allowed_types) {
-    stop("S7 objects are not subsettable.", call. = FALSE)
+    stop("S7 objects are not subsettable.", call. = TRUE)
```
Comment (hadley) [inline R/zzz.R:88]: We don't usually show the call when it's a non-exported function.

File: R/zzz.R [hunk 2]
```diff
@@ -82,9 +82,10 @@ is_S7_type <- function(x) {
 }
 
 check_subsettable <- function(x, allow_env = FALSE) {
-  allowed_types <- c("list", if (allow_env) "environment")
+  allowed_types <- c("list", if (allow_env) "environment",
+                     "language", "pairlist")
```
Comment (hadley) [inline R/zzz.R:86]:
```suggestion
  allowed_types <- c("list", "language", "pairlist", if (allow_env) "environment")
```
?

File: R/aaa.R [hunk 3]
```diff
@@ -24,9 +24,8 @@ new_function <- function(args = NULL,
 
 
 topNamespaceName <- function(env = parent.frame()) {
-  env <- topenv(env)
-  if (isNamespace(env))
-    getNamespaceName(env)
+  (if (isNamespace(env <- topenv(env)))
+    getNamespaceName(env))
```
Comment (hadley) [inline R/aaa.R:28]: Personally, I'd write this more like:

```R
env <- topenv()
if (!isNamespace(env) {
  return()
}

getNamespaceName(env)
```

I find that logic easier to follow

**Review by hadley — APPROVED** [review]

File: R/zzz.R (hunk 2 above)
Comment (t-kalinowski) [reply R/zzz.R:86]: See the `QuotedCall` class in tests for how `[[` on a `class_call` (`"language"`) is useful.

File: R/zzz.R [hunk 4]
```diff
@@ -82,9 +82,9 @@ is_S7_type <- function(x) {
 }
 
 check_subsettable <- function(x, allow_env = FALSE) {
-  allowed_types <- c("list", if (allow_env) "environment")
+  allowed_types <- c("list", "language", "pairlist", if (allow_env) "environment")
   if (!typeof(x) %in% allowed_types) {
-    stop("S7 objects are not subsettable.", call. = FALSE)
+    stop("S7 objects are not subsettable.", call. = TRUE)
```
Comment (hadley) [inline R/zzz.R:87]:
```suggestion
    stop("S7 objects are not subsettable.")
```

😄

Comment (t-kalinowski) [reply R/zzz.R]: We really need a better error call and traceback from custom getter/setter calls, because right now, debugging any errors signaled from them is unnecessarily difficult. But that should be a separate issue.

File: R/zzz.R (hunk 1 above)
Comment (t-kalinowski) [reply R/zzz.R]: We really need a better error call and traceback from custom getter/setter calls, because right now, debugging any errors signaled from them is unnecessarily difficult. But that should be a separate issue.
